In [103]:
import pandas as pd

#Data Cleaning

##Cleaning Airbnb

First we start by examining the Airbnb data. According to the schema of our database, the attributes of an Airbnb listing that can't be null are id and price. Examination of the data shows that there are no entries that have null values for id or price so no entries had to be removed.

In [104]:
ab_2023 = pd.read_csv('AB_US_2023.csv')

<ipython-input-104-7a2b458dda5f>:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  ab_2023 = pd.read_csv('AB_US_2023.csv')

In [105]:
ab_2023.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
count,2.321470e+05,2.321470e+05,232147.000000,232147.000000,232147.000000,232147.000000,232147.000000,183062.000000,232147.000000,232147.000000,232147.000000
mean,2.584580e+17,1.582248e+08,36.610585,-98.301436,259.468001,13.495867,40.915230,1.638348,29.879055,180.985686,11.689701
std,3.465985e+17,1.587164e+08,5.126523,19.706929,1024.645918,27.920631,80.649152,1.910812,106.013665,134.715299,20.599954
min,6.000000e+00,2.300000e+01,25.957323,-123.089130,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000,0.000000
25%,2.638896e+07,2.299242e+07,33.976225,-118.315111,91.000000,2.000000,1.000000,0.310000,1.000000,52.000000,0.000000
50%,4.896307e+07,1.005783e+08,36.190556,-97.727670,149.000000,3.000000,9.000000,1.000000,2.000000,175.000000,3.000000
75%,6.633014e+17,2.686930e+08,40.717440,-77.026222,250.000000,30.000000,43.000000,2.420000,10.000000,321.000000,16.000000
max,8.581014e+17,5.069384e+08,47.734010,-70.996000,100000.000000,1250.000000,3091.000000,101.420000,1003.000000,365.000000,1314.000000

In [106]:
ab_2023.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'city'],
      dtype='object')

In [107]:
ab_2023.info(
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232147 entries, 0 to 232146
Data columns (total 18 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              232147 non-null  int64
 1   name                            232131 non-null  object
 2   host_id                         232147 non-null  int64
 3   host_name                       232134 non-null  object
 4   neighbourhood_group             96500 non-null   object
 5   neighbourhood                   232147 non-null  object
 6   latitude                        232147 non-null  float64
 7   longitude                       232147 non-null  float64
 8   room_type                       232147 non-null  object
 9   price                           232147 non-null  int64
 10  minimum_nights                  232147 non-null  int64
 11  number_of_reviews               232147 non-null  int64
 12  last_review                     183062 non-null  object
 13  reviews_per_month               183062 non-null  float64
 14  calculated_host_listings_count  232147 non-null  int64
 15  availability_365                232147 non-null  int64
 16  number_of_reviews_ltm           232147 non-null  int64
 17  city                            232147 non-null  object
dtypes: float64(3), int64(8), object(7)
memory usage: 31.9+ MB

In [108]:
ab_2023.head(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,city
0,958,"Bright, Modern Garden Unit - 1BR/1BTH",1169,Holly,NaN,Western Addition,37.77028,-122.43317,Entire home/apt,202,2,383,2023-02-19,2.31,1,128,59,San Francisco
1,5858,Creative Sanctuary,8904,Philip And Tania,NaN,Bernal Heights,37.74474,-122.42089,Entire home/apt,235,30,111,2017-08-06,0.66,1,365,0,San Francisco
2,8142,Friendly Room Apt. Style -UCSF/USF - San Franc...,21994,Aaron,NaN,Haight Ashbury,37.76555,-122.45213,Private room,56,32,9,2022-10-27,0.09,13,365,1,San Francisco
3,8339,Historic Alamo Square Victorian,24215,Rosy,NaN,Western Addition,37.77564,-122.43642,Entire home/apt,575,9,28,2019-06-28,0.17,2,365,0,San Francisco
4,8739,"Mission Sunshine, with Private Bath",7149,Ivan & Wendy,NaN,Mission,37.76030,-122.42197,Private room,110,1,770,2023-02-25,4.65,2,159,34,San Francisco

In [109]:
ab_2020 = pd.read_csv("/content/AB_US_2020.csv")

<ipython-input-109-62ea5c200227>:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  ab_2020 = pd.read_csv("/content/AB_US_2020.csv")

In [110]:
ab_2020.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,2.260300e+05,2.260300e+05,226030.000000,226030.000000,226030.000000,2.260300e+05,226030.000000,177428.00000,226030.000000,226030.000000
mean,2.547176e+07,9.352385e+07,35.662829,-103.220662,219.716529,4.525490e+02,34.506530,1.43145,16.698562,159.314856
std,1.317814e+07,9.827422e+07,6.849855,26.222091,570.353609,2.103376e+05,63.602914,1.68321,51.068966,140.179628
min,1.090000e+02,2.300000e+01,18.920990,-159.714900,0.000000,1.000000e+00,0.000000,0.01000,1.000000,0.000000
25%,1.515890e+07,1.399275e+07,32.761783,-118.598115,75.000000,1.000000e+00,1.000000,0.23000,1.000000,0.000000
50%,2.590916e+07,5.138266e+07,37.261125,-97.817200,121.000000,2.000000e+00,8.000000,0.81000,2.000000,140.000000
75%,3.772624e+07,1.497179e+08,40.724038,-76.919323,201.000000,7.000000e+00,39.000000,2.06000,6.000000,311.000000
max,4.556085e+07,3.679176e+08,47.734620,-70.995950,24999.000000,1.000000e+08,966.000000,44.06000,593.000000,365.000000

In [111]:
ab_2020.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'city'],
      dtype='object')

In [112]:
ab_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226030 entries, 0 to 226029
Data columns (total 17 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              226030 non-null  int64
 1   name                            226002 non-null  object
 2   host_id                         226030 non-null  int64
 3   host_name                       225997 non-null  object
 4   neighbourhood_group             110185 non-null  object
 5   neighbourhood                   226030 non-null  object
 6   latitude                        226030 non-null  float64
 7   longitude                       226030 non-null  float64
 8   room_type                       226030 non-null  object
 9   price                           226030 non-null  int64
 10  minimum_nights                  226030 non-null  int64
 11  number_of_reviews               226030 non-null  int64
 12  last_review                     177428 non-null  object
 13  reviews_per_month               177428 non-null  float64
 14  calculated_host_listings_count  226030 non-null  int64
 15  availability_365                226030 non-null  int64
 16  city                            226030 non-null  object
dtypes: float64(3), int64(7), object(7)
memory usage: 29.3+ MB

In [113]:
#Add Year column to both datasets.

ab_2023["year"] = pd.to_datetime('2023').year
ab_2020["year"] = pd.to_datetime('2020').year
ab_2020

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,city,year
0,38585,Charming Victorian home - twin beds + breakfast,165529,Evelyne,NaN,28804,35.651460,-82.627920,Private room,60,1,138,16/02/20,1.14,1,0,Asheville,2020
1,80905,French Chic Loft,427027,Celeste,NaN,28801,35.597790,-82.555400,Entire home/apt,470,1,114,07/09/20,1.03,11,288,Asheville,2020
2,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,320564,Lisa,NaN,28801,35.606700,-82.555630,Entire home/apt,75,30,89,30/11/19,0.81,2,298,Asheville,2020
3,155305,Cottage! BonPaul + Sharky's Hostel,746673,BonPaul,NaN,28806,35.578640,-82.595780,Entire home/apt,90,1,267,22/09/20,2.39,5,0,Asheville,2020
4,160594,Historic Grove Park,769252,Elizabeth,NaN,28801,35.614420,-82.541270,Private room,125,30,58,19/10/15,0.52,1,0,Asheville,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226025,45506143,"DC Hidden In Plain ""Site""",25973146,Marci,NaN,"Downtown, Chinatown, Penn Quarters, Mount Vern...",38.903880,-77.029730,Entire home/apt,104,1,0,NaN,NaN,2,99,Washington D.C.,2020
226026,45511428,DC 3 BR w/ screen porch 3 blck to metro w/ par...,231133074,Thomas,NaN,"Brookland, Brentwood, Langdon",38.920820,-76.990980,Entire home/apt,151,2,0,NaN,NaN,1,300,Washington D.C.,2020
226027,45514685,Charming Penthouse Apt w/ Rooftop Terrace in L...,33758935,Bassem,NaN,"Shaw, Logan Circle",38.911170,-77.033540,Entire home/apt,240,2,0,NaN,NaN,1,173,Washington D.C.,2020
226028,45516412,Adams Morgan/Nat'l Zoo 1 BR Apt #32,23193071,Michael,NaN,"Kalorama Heights, Adams Morgan, Lanier Heights",38.926630,-77.044360,Entire home/apt,60,21,0,NaN,NaN,5,362,Washington D.C.,2020
226029,45517735,Beautiful large one-bedroom w/ washer and dryer,17789858,Adam,NaN,"Edgewood, Bloomingdale, Truxton Circle, Eckington",38.911569,-77.009431,Entire home/apt,79,7,0,NaN,NaN,2,62,Washington D.C.,2020

In [114]:
import numpy as np

def random_neighborhood(neigh_list_str):
    neigh_list = neigh_list_str.split(",")
    return np.random.choice(neigh_list)

# Apply the function to each row in the 'neighborhood' column
ab_2020['neighbourhood'] = ab_2020['neighbourhood'].apply(random_neighborhood)
ab_2020

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,city,year
0,38585,Charming Victorian home - twin beds + breakfast,165529,Evelyne,NaN,28804,35.651460,-82.627920,Private room,60,1,138,16/02/20,1.14,1,0,Asheville,2020
1,80905,French Chic Loft,427027,Celeste,NaN,28801,35.597790,-82.555400,Entire home/apt,470,1,114,07/09/20,1.03,11,288,Asheville,2020
2,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,320564,Lisa,NaN,28801,35.606700,-82.555630,Entire home/apt,75,30,89,30/11/19,0.81,2,298,Asheville,2020
3,155305,Cottage! BonPaul + Sharky's Hostel,746673,BonPaul,NaN,28806,35.578640,-82.595780,Entire home/apt,90,1,267,22/09/20,2.39,5,0,Asheville,2020
4,160594,Historic Grove Park,769252,Elizabeth,NaN,28801,35.614420,-82.541270,Private room,125,30,58,19/10/15,0.52,1,0,Asheville,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226025,45506143,"DC Hidden In Plain ""Site""",25973146,Marci,NaN,Mount Vernon Square,38.903880,-77.029730,Entire home/apt,104,1,0,NaN,NaN,2,99,Washington D.C.,2020
226026,45511428,DC 3 BR w/ screen porch 3 blck to metro w/ par...,231133074,Thomas,NaN,Brentwood,38.920820,-76.990980,Entire home/apt,151,2,0,NaN,NaN,1,300,Washington D.C.,2020
226027,45514685,Charming Penthouse Apt w/ Rooftop Terrace in L...,33758935,Bassem,NaN,Logan Circle,38.911170,-77.033540,Entire home/apt,240,2,0,NaN,NaN,1,173,Washington D.C.,2020
226028,45516412,Adams Morgan/Nat'l Zoo 1 BR Apt #32,23193071,Michael,NaN,Adams Morgan,38.926630,-77.044360,Entire home/apt,60,21,0,NaN,NaN,5,362,Washington D.C.,2020
226029,45517735,Beautiful large one-bedroom w/ washer and dryer,17789858,Adam,NaN,Eckington,38.911569,-77.009431,Entire home/apt,79,7,0,NaN,NaN,2,62,Washington D.C.,2020

In [115]:
ab_df = pd.concat([ab_2020, ab_2023], axis =0)

In [116]:
ab_df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,city,year,number_of_reviews_ltm
0,38585,Charming Victorian home - twin beds + breakfast,165529,Evelyne,NaN,28804,35.651460,-82.627920,Private room,60,1,138,16/02/20,1.14,1,0,Asheville,2020,NaN
1,80905,French Chic Loft,427027,Celeste,NaN,28801,35.597790,-82.555400,Entire home/apt,470,1,114,07/09/20,1.03,11,288,Asheville,2020,NaN
2,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,320564,Lisa,NaN,28801,35.606700,-82.555630,Entire home/apt,75,30,89,30/11/19,0.81,2,298,Asheville,2020,NaN
3,155305,Cottage! BonPaul + Sharky's Hostel,746673,BonPaul,NaN,28806,35.578640,-82.595780,Entire home/apt,90,1,267,22/09/20,2.39,5,0,Asheville,2020,NaN
4,160594,Historic Grove Park,769252,Elizabeth,NaN,28801,35.614420,-82.541270,Private room,125,30,58,19/10/15,0.52,1,0,Asheville,2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232142,849230448624862502,Private Half Moon Bay Oasis By Pillar Point Be...,29395385,Khalid,NaN,Unincorporated Areas,37.506164,-122.476188,Entire home/apt,389,2,0,NaN,NaN,1,365,San Mateo County,2023,0.0
232143,850805127216414630,Home near SFO,440957696,Christina,NaN,San Bruno,37.623630,-122.426570,Entire home/apt,158,1,0,NaN,NaN,1,364,San Mateo County,2023,0.0
232144,851562104616413652,Modern New Private Studio in SFO,41574587,Vality,NaN,South San Francisco,37.655661,-122.413130,Entire home/apt,97,1,0,NaN,NaN,32,359,San Mateo County,2023,0.0
232145,851792795339759410,Lux Bedroom with a Shared Bath near SFO,73133543,Stephannie,NaN,South San Francisco,37.644792,-122.454213,Private room,62,2,0,NaN,NaN,3,67,San Mateo County,2023,0.0
232146,851801296770555568,Lux Bedroom with Private Bath near SFO,73133543,Stephannie,NaN,South San Francisco,37.642655,-122.452391,Private room,85,2,0,NaN,NaN,3,69,San Mateo County,2023,0.0

In [117]:
ab_df.dropna(subset=["id", "price", "city"], inplace=True)

In [118]:
ab_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 458177 entries, 0 to 232146
Data columns (total 19 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              458177 non-null  int64
 1   name                            458133 non-null  object
 2   host_id                         458177 non-null  int64
 3   host_name                       458131 non-null  object
 4   neighbourhood_group             206685 non-null  object
 5   neighbourhood                   458177 non-null  object
 6   latitude                        458177 non-null  float64
 7   longitude                       458177 non-null  float64
 8   room_type                       458177 non-null  object
 9   price                           458177 non-null  int64
 10  minimum_nights                  458177 non-null  int64
 11  number_of_reviews               458177 non-null  int64
 12  last_review                     360490 non-null  object
 13  reviews_per_month               360490 non-null  float64
 14  calculated_host_listings_count  458177 non-null  int64
 15  availability_365                458177 non-null  int64
 16  city                            458177 non-null  object
 17  year                            458177 non-null  int64
 18  number_of_reviews_ltm           232147 non-null  float64
dtypes: float64(4), int64(8), object(7)
memory usage: 69.9+ MB

In [119]:
ids = [i for i in range(1, len(ab_df) +1 )]

In [120]:
ab_df["id"] = ids

In [121]:
ab_df = ab_df.rename(columns={'neighbourhood': 'neighborhood'})

In [122]:
ab_listings = ab_df[["id", "name", "price", "neighborhood", "city"]]
ab_listings

,id,name,price,neighborhood,city
0,1,Charming Victorian home - twin beds + breakfast,60,28804,Asheville
1,2,French Chic Loft,470,28801,Asheville
2,3,Walk to stores/parks/downtown. Fenced yard/Pet...,75,28801,Asheville
3,4,Cottage! BonPaul + Sharky's Hostel,90,28806,Asheville
4,5,Historic Grove Park,125,28801,Asheville
...,...,...,...,...,...
232142,458173,Private Half Moon Bay Oasis By Pillar Point Be...,389,Unincorporated Areas,San Mateo County
232143,458174,Home near SFO,158,San Bruno,San Mateo County
232144,458175,Modern New Private Studio in SFO,97,South San Francisco,San Mateo County
232145,458176,Lux Bedroom with a Shared Bath near SFO,62,South San Francisco,San Mateo County
232146,458177,Lux Bedroom with Private Bath near SFO,85,South San Francisco,San Mateo County

In [123]:
ab_listings["neighborhood"].unique()

array(['28804', '28801', '28806', ..., 'Thomy Locust Pl', 'Harbor Island',
       'Nellis AFB'], dtype=object)

In [124]:
ab_subclass = ab_df[["id", "minimum_nights", "room_type", "last_review"]]
ab_subclass["last_review"] = pd.to_datetime(ab_subclass["last_review"])
ab_subclass

<ipython-input-124-b0265c5309b8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ab_subclass["last_review"] = pd.to_datetime(ab_subclass["last_review"])

            id  minimum_nights        room_type last_review
0            1               1     Private room  2020-02-16
1            2               1  Entire home/apt  2020-07-09
2            3              30  Entire home/apt  2019-11-30
3            4               1  Entire home/apt  2020-09-22
4            5              30     Private room  2015-10-19
...        ...             ...              ...         ...
232142  458173               2  Entire home/apt         NaT
232143  458174               1  Entire home/apt         NaT
232144  458175               1  Entire home/apt         NaT
232145  458176               2     Private room         NaT
232146  458177               2     Private room         NaT

[458177 rows x 4 columns]

In [125]:
cl_df = pd.read_csv('/content/clean_2000_2018.csv')

<ipython-input-125-0644eca360df>:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  cl_df = pd.read_csv('/content/clean_2000_2018.csv')

In [126]:
cl_df

,post_id,date,year,nhood,city,county,price,beds,baths,sqft,room_in_apt,address,lat,lon,title,descr,details
0,pre2013_134138,20050111,2005,alameda,alameda,alameda,1250,2,2.0,NaN,0,NaN,NaN,NaN,$1250 / 2br - 2BR/2BA 1145 ALAMEDA DE LAS PU...,NaN,NaN
1,pre2013_135669,20050126,2005,alameda,alameda,alameda,1295,2,NaN,NaN,0,NaN,NaN,NaN,$1295 / 2br - Walk the Beach! 1 FREE MONTH + $...,NaN,NaN
2,pre2013_127127,20041017,2004,alameda,alameda,alameda,1100,2,NaN,NaN,0,NaN,NaN,NaN,$1100 / 2br - cottage,NaN,NaN
3,pre2013_68671,20120601,2012,alameda,alameda,alameda,1425,1,NaN,735.0,0,NaN,NaN,NaN,$1425 / 1br - 735ft² - BEST LOCATION SOUTHSHOR...,NaN,NaN
4,pre2013_127580,20041021,2004,alameda,alameda,alameda,890,1,NaN,NaN,0,NaN,NaN,NaN,"$890 / 1br - Classy ""Painted Lady"" VICTORIAN -...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200791,pre2013_126116,20040925,2004,yountville,yountville,napa,1850,2.0,NaN,NaN,0,NaN,NaN,NaN,$1850 / 2br - Yountville - LARGE townhouse in ...,NaN,NaN
200792,pre2013_162529,20060221,2006,yountville,yountville,napa,1950,2.0,NaN,NaN,0,NaN,NaN,NaN,$1950 / 2br - Yountville duplex,NaN,NaN
200793,pre2013_65092,20120402,2012,yountville,yountville,napa,2600,2.0,2.0,1300.0,0,NaN,NaN,NaN,$2600 / 2br - 1300ft² - Fully furnished two be...,NaN,NaN
200794,pre2013_57294,20120307,2012,yountville,yountville,napa,1900,2.0,NaN,1000.0,0,NaN,NaN,NaN,$1900 / 2br - 1000ft² - Charming Old Town Youn...,NaN,NaN
200795,pre2013_78888,20080416,2008,yountville,yountville,napa,1650,2.0,NaN,NaN,0,NaN,NaN,NaN,$1650 / 2br - Yountville cottage home with pool -,NaN,NaN

In [127]:
cl_df.describe()

,date,year,price,baths,sqft,room_in_apt,lat,lon
count,2.007960e+05,200796.000000,200796.000000,42675.000000,64679.000000,200796.000000,7651.000000,4312.000000
mean,2.009572e+07,2009.507899,2135.362746,1.679086,1201.827688,0.001419,37.666060,-122.210272
std,4.469407e+04,4.476676,1427.747903,0.690509,5000.217864,0.037648,0.346889,0.776726
min,2.000090e+07,2000.000000,220.000000,1.000000,80.000000,0.000000,33.570100,-123.196500
25%,2.005023e+07,2005.000000,1295.000000,1.000000,750.000000,0.000000,37.400841,-122.423500
50%,2.011092e+07,2011.000000,1800.000000,2.000000,1000.000000,0.000000,37.756512,-122.263314
75%,2.012080e+07,2012.000000,2505.000000,2.000000,1360.000000,0.000000,37.797901,-121.996375
max,2.018072e+07,2018.000000,40000.000000,8.000000,900000.000000,1.000000,40.434945,-74.198019

In [128]:
cl_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200796 entries, 0 to 200795
Data columns (total 17 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   post_id      200796 non-null  object
 1   date         200796 non-null  int64
 2   year         200796 non-null  int64
 3   nhood        200796 non-null  object
 4   city         200796 non-null  object
 5   county       199402 non-null  object
 6   price        200796 non-null  int64
 7   beds         194204 non-null  object
 8   baths        42675 non-null   float64
 9   sqft         64679 non-null   float64
 10  room_in_apt  200796 non-null  int64
 11  address      3908 non-null    object
 12  lat          7651 non-null    float64
 13  lon          4312 non-null    float64
 14  title        198279 non-null  object
 15  descr        3254 non-null    object
 16  details      8016 non-null    object
dtypes: float64(4), int64(4), object(9)
memory usage: 26.0+ MB

In [129]:
cl_df['date'] = cl_df['date'].astype(str)

In [130]:
cl_df['date'] = pd.to_datetime(cl_df['date'])

In [131]:
cl_df["nhood"] = cl_df["nhood"].str.capitalize()
cl_df["city"] = cl_df["city"].str.capitalize()

cl_df

,post_id,date,year,nhood,city,county,price,beds,baths,sqft,room_in_apt,address,lat,lon,title,descr,details
0,pre2013_134138,2005-01-11,2005,Alameda,Alameda,alameda,1250,2,2.0,NaN,0,NaN,NaN,NaN,$1250 / 2br - 2BR/2BA 1145 ALAMEDA DE LAS PU...,NaN,NaN
1,pre2013_135669,2005-01-26,2005,Alameda,Alameda,alameda,1295,2,NaN,NaN,0,NaN,NaN,NaN,$1295 / 2br - Walk the Beach! 1 FREE MONTH + $...,NaN,NaN
2,pre2013_127127,2004-10-17,2004,Alameda,Alameda,alameda,1100,2,NaN,NaN,0,NaN,NaN,NaN,$1100 / 2br - cottage,NaN,NaN
3,pre2013_68671,2012-06-01,2012,Alameda,Alameda,alameda,1425,1,NaN,735.0,0,NaN,NaN,NaN,$1425 / 1br - 735ft² - BEST LOCATION SOUTHSHOR...,NaN,NaN
4,pre2013_127580,2004-10-21,2004,Alameda,Alameda,alameda,890,1,NaN,NaN,0,NaN,NaN,NaN,"$890 / 1br - Classy ""Painted Lady"" VICTORIAN -...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200791,pre2013_126116,2004-09-25,2004,Yountville,Yountville,napa,1850,2.0,NaN,NaN,0,NaN,NaN,NaN,$1850 / 2br - Yountville - LARGE townhouse in ...,NaN,NaN
200792,pre2013_162529,2006-02-21,2006,Yountville,Yountville,napa,1950,2.0,NaN,NaN,0,NaN,NaN,NaN,$1950 / 2br - Yountville duplex,NaN,NaN
200793,pre2013_65092,2012-04-02,2012,Yountville,Yountville,napa,2600,2.0,2.0,1300.0,0,NaN,NaN,NaN,$2600 / 2br - 1300ft² - Fully furnished two be...,NaN,NaN
200794,pre2013_57294,2012-03-07,2012,Yountville,Yountville,napa,1900,2.0,NaN,1000.0,0,NaN,NaN,NaN,$1900 / 2br - 1000ft² - Charming Old Town Youn...,NaN,NaN
200795,pre2013_78888,2008-04-16,2008,Yountville,Yountville,napa,1650,2.0,NaN,NaN,0,NaN,NaN,NaN,$1650 / 2br - Yountville cottage home with pool -,NaN,NaN

In [132]:
series1 = ab_df["neighborhood"]
series2 = cl_df["nhood"]
shared_elements = series1[series1.isin(series2)]
len(set(shared_elements))

21

In [133]:
cl_df.dropna(subset=["post_id", "price", "city"], inplace=True)

In [134]:
cl_df.rename(columns={'post_id': 'id', 'title': 'name', 'nhood': 'neighborhood'}, inplace=True)

In [135]:
ids = [i for i in range(len(ab_df) +1 , len(ab_df) + len(cl_df) +1)]

In [136]:
cl_df["id"] = ids

In [137]:
cl_listings = cl_df[["id", "name", "price", "neighborhood", "city"]]

In [138]:
cl_subclass = cl_df[["id", "year", "date", "beds", "baths"]]

In [139]:
ab_listings.rename(columns={'neighbourhood': 'neighborhood'})

,id,name,price,neighborhood,city
0,1,Charming Victorian home - twin beds + breakfast,60,28804,Asheville
1,2,French Chic Loft,470,28801,Asheville
2,3,Walk to stores/parks/downtown. Fenced yard/Pet...,75,28801,Asheville
3,4,Cottage! BonPaul + Sharky's Hostel,90,28806,Asheville
4,5,Historic Grove Park,125,28801,Asheville
...,...,...,...,...,...
232142,458173,Private Half Moon Bay Oasis By Pillar Point Be...,389,Unincorporated Areas,San Mateo County
232143,458174,Home near SFO,158,San Bruno,San Mateo County
232144,458175,Modern New Private Studio in SFO,97,South San Francisco,San Mateo County
232145,458176,Lux Bedroom with a Shared Bath near SFO,62,South San Francisco,San Mateo County
232146,458177,Lux Bedroom with Private Bath near SFO,85,South San Francisco,San Mateo County

In [140]:
cl_subclass

            id  year       date beds  baths
0       458178  2005 2005-01-11    2    2.0
1       458179  2005 2005-01-26    2    NaN
2       458180  2004 2004-10-17    2    NaN
3       458181  2012 2012-06-01    1    NaN
4       458182  2004 2004-10-21    1    NaN
...        ...   ...        ...  ...    ...
200791  658969  2004 2004-09-25  2.0    NaN
200792  658970  2006 2006-02-21  2.0    NaN
200793  658971  2012 2012-04-02  2.0    2.0
200794  658972  2012 2012-03-07  2.0    NaN
200795  658973  2008 2008-04-16  2.0    NaN

[200796 rows x 5 columns]

In [141]:
all_listings = pd.concat([ab_listings, cl_listings], axis = 0)

In [142]:
all_listings

,id,name,price,neighborhood,city
0,1,Charming Victorian home - twin beds + breakfast,60,28804,Asheville
1,2,French Chic Loft,470,28801,Asheville
2,3,Walk to stores/parks/downtown. Fenced yard/Pet...,75,28801,Asheville
3,4,Cottage! BonPaul + Sharky's Hostel,90,28806,Asheville
4,5,Historic Grove Park,125,28801,Asheville
...,...,...,...,...,...
200791,658969,$1850 / 2br - Yountville - LARGE townhouse in ...,1850,Yountville,Yountville
200792,658970,$1950 / 2br - Yountville duplex,1950,Yountville,Yountville
200793,658971,$2600 / 2br - 1300ft² - Fully furnished two be...,2600,Yountville,Yountville
200794,658972,$1900 / 2br - 1000ft² - Charming Old Town Youn...,1900,Yountville,Yountville
200795,658973,$1650 / 2br - Yountville cottage home with pool -,1650,Yountville,Yountville

In [143]:
all_listings.to_csv("/content/all_listings.csv", index=False)

In [144]:
ab_subclass.to_csv("/content/ab_subclass.csv", index=False)

In [145]:
cl_subclass.to_csv("/content/cl_subclass.csv", index=False)

In [146]:
all_listings

,id,name,price,neighborhood,city
0,1,Charming Victorian home - twin beds + breakfast,60,28804,Asheville
1,2,French Chic Loft,470,28801,Asheville
2,3,Walk to stores/parks/downtown. Fenced yard/Pet...,75,28801,Asheville
3,4,Cottage! BonPaul + Sharky's Hostel,90,28806,Asheville
4,5,Historic Grove Park,125,28801,Asheville
...,...,...,...,...,...
200791,658969,$1850 / 2br - Yountville - LARGE townhouse in ...,1850,Yountville,Yountville
200792,658970,$1950 / 2br - Yountville duplex,1950,Yountville,Yountville
200793,658971,$2600 / 2br - 1300ft² - Fully furnished two be...,2600,Yountville,Yountville
200794,658972,$1900 / 2br - 1000ft² - Charming Old Town Youn...,1900,Yountville,Yountville
200795,658973,$1650 / 2br - Yountville cottage home with pool -,1650,Yountville,Yountville

#Creating User and Saves data

In [147]:
import random

In [148]:
emails = ["user" + str(i) + "@example.com" for i in range(0, 20000)]

In [149]:
passwords = ["password" + str(i) for i in range(0, 20000)]

In [150]:
cities = set(all_listings['city'])

In [168]:
users_df = pd.DataFrame({
    "Email" : emails,
    "Password" : passwords
})
users_df["city"] = [random.choice(list(cities)) for i in range(0, 20000)]

In [169]:
len(users_df)

20000

In [170]:
save_listings = [random.choice(range(1, 458177)) for i in range(1, 400000)]

In [171]:
save_users = [random.choice(emails) for i in range(1, 400000)]

In [173]:
saves_df = pd.DataFrame({
    "ListingID" : save_listings,
    "Email" : save_users
})
saves_df = saves_df.drop_duplicates()
len(saves_df)

399988

In [175]:
saves_df.to_csv("/content/saves_table.csv", index=False)

In [176]:
users_df.to_csv("/content/users_table.csv", index=False)